"""init

Revision ID: d67a81945b7e
Revises: 
Create Date: 2026-06-28 19:30:31.821801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd67a81945b7e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresas_contratistas',
    sa.Column('rut', sa.String(length=12), nullable=False),
    sa.Column('razon_social', sa.String(length=255), nullable=False),
    sa.Column('giro', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rut')
    )
    op.create_table('mandantes',
    sa.Column('razon_social', sa.String(length=255), nullable=False),
    sa.Column('rut', sa.String(length=12), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rut'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('pilares',
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('contratistas_mandantes',
    sa.Column('contratista_id', sa.Uuid(), nullable=False),
    sa.Column('mandante_id', sa.Uuid(), nullable=False),
    sa.Column('estado_acreditacion', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contratista_id'], ['empresas_contratistas.id'], ),
    sa.ForeignKeyConstraint(['mandante_id'], ['mandantes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contratista_id', 'mandante_id', name='uq_contratista_mandante')
    )
    op.create_table('subpilares',
    sa.Column('pilar_id', sa.Uuid(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pilar_id'], ['pilares.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trabajadores',
    sa.Column('empresa_id', sa.Uuid(), nullable=False),
    sa.Column('rut', sa.String(length=12), nullable=False),
    sa.Column('nombre_completo', sa.String(length=255), nullable=False),
    sa.Column('cargo', sa.String(length=255), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas_contratistas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('rol', sa.String(length=30), nullable=False),
    sa.Column('mandante_id', sa.Uuid(), nullable=True),
    sa.Column('contratista_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contratista_id'], ['empresas_contratistas.id'], ),
    sa.ForeignKeyConstraint(['mandante_id'], ['mandantes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('requisitos_documentales',
    sa.Column('subpilar_id', sa.Uuid(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('entidad_tipo', sa.String(length=20), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['subpilar_id'], ['subpilares.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('documentos',
    sa.Column('requisito_id', sa.Uuid(), nullable=False),
    sa.Column('mandante_id', sa.Uuid(), nullable=False),
    sa.Column('empresa_id', sa.Uuid(), nullable=True),
    sa.Column('trabajador_id', sa.Uuid(), nullable=True),
    sa.Column('estado', sa.Integer(), nullable=False),
    sa.Column('archivo_url', sa.String(length=512), nullable=False),
    sa.Column('campos_extraidos', sa.JSON(), nullable=True),
    sa.Column('mensaje_brecha', sa.Text(), nullable=True),
    sa.Column('fecha_vigencia_hasta', sa.Date(), nullable=True),
    sa.Column('frecuencia_renovacion_dias', sa.Integer(), nullable=True),
    sa.Column('aprobado_por_excepcion', sa.Boolean(), nullable=False),
    sa.Column('justificacion_excepcion', sa.Text(), nullable=True),
    sa.Column('aprobado_por_usuario_id', sa.Uuid(), nullable=True),
    sa.Column('aprobado_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['aprobado_por_usuario_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas_contratistas.id'], ),
    sa.ForeignKeyConstraint(['mandante_id'], ['mandantes.id'], ),
    sa.ForeignKeyConstraint(['requisito_id'], ['requisitos_documentales.id'], ),
    sa.ForeignKeyConstraint(['trabajador_id'], ['trabajadores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mandante_requisito_config',
    sa.Column('mandante_id', sa.Uuid(), nullable=False),
    sa.Column('requisito_documental_id', sa.Uuid(), nullable=False),
    sa.Column('es_obligatorio', sa.Boolean(), nullable=False),
    sa.Column('vigencia_max_dias', sa.Integer(), nullable=False),
    sa.Column('umbral_deuda_max', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['mandante_id'], ['mandantes.id'], ),
    sa.ForeignKeyConstraint(['requisito_documental_id'], ['requisitos_documentales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mandante_requisito_config')
    op.drop_table('documentos')
    op.drop_table('requisitos_documentales')
    op.drop_table('usuarios')
    op.drop_table('trabajadores')
    op.drop_table('subpilares')
    op.drop_table('contratistas_mandantes')
    op.drop_table('pilares')
    op.drop_table('mandantes')
    op.drop_table('empresas_contratistas')
    # ### end Alembic commands ###
