name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /root/beriza
            git pull origin main
            docker build -t beriza-app .
            docker stop beriza-app
            docker rm beriza-app
            docker run -d --name beriza-app --restart always -p 3002:80 beriza-app
